export const GET_USER = 'GET_USER'
export const SIGNUP = 'SIGNUP_USER'
export const SIGNIN = 'SIGNIN_USER'
export const ADD_CONTACT   = 'ADD_CONTACT'
export const UPDATE_CONTACT   = 'UPDATE_CONTACT'
export const READ_CONTACT = 'READ_CONTACT'
export const SEARCH_CONTACT   = 'SEARCH_CONTACT'
export const DELETE_CONTACT   = 'DELETE_CONTACT'